### ISSUE TITLE
celery related problem, do you have the same isues?

### ISSUE THREAD

**Issue by mykolasglinskis** [appsecco/docker-datasploit#1]
[2016-10-27 10:47:25,109: INFO/Worker-15] Starting new HTTPS connection (1): search.wikileaks.org
[2016-10-27 10:47:25,128: CRITICAL/MainProcess] Task osint.domain_shodan.shodandomainsearch[d945d4d1-f0b8-4f7a-978a-e10193ee2d87] INTERNAL ERROR: OperationalError('no such table: celery_taskmeta',)
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 253, in trace_task
I, R, state, retval = on_error(task_request, exc, uuid)
File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 201, in on_error
R = I.handle_error_state(task, eager=eager)
File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 85, in handle_error_state
}self.state
File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 118, in handle_failure
req.id, exc, einfo.traceback, request=req,
File "/usr/local/lib/python2.7/dist-packages/celery/backends/base.py", line 133, in mark_as_failure
traceback=traceback, request=request)
File "/usr/local/lib/python2.7/dist-packages/celery/backends/base.py", line 271, in store_result
request=request, kwargs)
File "/usr/local/lib/python2.7/dist-packages/djcelery/backends/database.py", line 29, in _store_result
traceback=traceback, children=self.current_task_children(request),
File "/usr/local/lib/python2.7/dist-packages/djcelery/managers.py", line 42, in _inner
return fun(args, *kwargs)
File "/usr/local/lib/python2.7/dist-packages/djcelery/managers.py", line 181, in store_result
'meta': {'children': children}})
File "/usr/local/lib/python2.7/dist-packages/djcelery/managers.py", line 87, in update_or_create
return get_queryset(self).update_or_create(kwargs)
File "/usr/local/lib/python2.7/dist-packages/djcelery/managers.py", line 70, in update_or_create
obj, created = self.get_or_create(kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 465, in get_or_create
return self.get(lookup), False
File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 381, in get
num = len(clone)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 240, in len
self.fetch_all()
File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 1074, in fetch_all
self._result_cache = list(self.iterator())
File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 52, in __iter
results = compiler.execute_sql()
File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 848, in execute_sql
cursor.execute(sql, params)
File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
return super(CursorDebugWrapper, self).execute(sql, params)
File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
return self.cursor.execute(sql, params)
File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 95, in exit
six.reraise(dj_exc_type, dj_exc_value, traceback)
File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
return self.cursor.execute(sql, params)
File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 323, in execute
return Database.Cursor.execute(self, query, params)
OperationalError: no such table: celery_taskmeta

**Comment by madhuakula** [comment]
@mykolasglinskis sorry for the delay. I think datasploit stopped supporting Web UI, I will updated the docker image.
https://www.slideshare.net/upgoingstar1/datasploit-tool-demo-at-null-bangalore-march-meet#15

Thanks

**Comment by madhuakula** [comment]
Closing this issue. Updated the Docker image with v1.0
